[project]
authors = ["Marlon Menendez <marlon.menendezg@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "learning-algorithms"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
c = "code ."

[dependencies]
max = ">=24.5.0,<25"
