[project]
authors = ["Marlon Menendez <44656927+mmenendezg@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "learning-algorithms"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"

[pypi-dependencies]
ruff = ">=0.7.1, <0.8"
ipykernel = ">=6.29.5, <7"
numpy = "*"
